//
//  audio.h
//  CassetteUtility
//
//  Created by Serge Tsyba on 22.1.2026.
//

#ifndef audio_h
#define audio_h

#include <stddef.h>

/**
 * Plays audio samples generated by the specified block closure.
 *
 * The specified block closure is called repeatedly with a pointer to a pre-allocated buffer and its size in
 * bytes to write audio samples to. The block closure must write audio samples with magnitudes in range
 * [-1.0, 1.0] and return the __total size__ of written audio samples, in bytes. To signal the end of audio,
 * the block closure must return 0 once there are no more audio samples written.
 *
 * @param device_id Audio device id to play on.
 * @param sample_rate Output audio sample rate in Hz. When NULL, uses nominal sample rate of
 * 		the output audio device.
 * @param write_buffer Block closure, which is called to write a portion audio samples to the
 * 		specified buffer, and returns the size of written data, in bytes.
 * @return 0 when playback succeeds, error code when fails.
 */
int cassette_play(int device_id, const int *sample_rate, size_t (^write_buffer)(float *, size_t), void (^completion_handler)(int));

/**
 * Creates an AIFF file at the specified path using the block closure which generates the audio samples.
 *
 * The specified block closure is called repeatedly with a pointer to a pre-allocated buffer and its size in
 * bytes to write audio samples to. The block closure must write audio samples with magnitudes in range
 * [-1.0, 1.0] and return the __total size__ of written audio samples, in bytes. To signal the end of audio,
 * the block closure must return 0 once there are no more audio samples written.
 *
 * @param path Path to an AIFF file to create.
 * @param sample_rate Output audio sample rate, in Hz.
 * @param write_buffer Block closure, which is called to write a portion audio samples to the
 * 		specified buffer, and returns the size of written data, in bytes.
 * @return 0 when creating a file succeeds; error code when fails.
 */
int cassette_write_file(const char *path, int sample_rate, size_t (^write_buffer)(float *, size_t));

#endif /* audio_h */
